alter session set "_ORACLE_SCRIPT"=true;
CREATE TABLESPACE PSEG DATAFILE 'D:\BD\PSEG.DBF' SIZE 4M AUTOEXTEND ON NEXT 1M;
CREATE USER PSEG IDENTIFIED BY 1234 DEFAULT TABLESPACE PSEG;
GRANT CONNECT,RESOURCE,DBA TO PSEG;

CONNECT PSEG/1234@localhost/ORCL;

CREATE TABLE PERMISO(
ID INTEGER PRIMARY KEY NOT NULL,
ID_PADRE INTEGER NULL,
NOMBRE VARCHAR(100) NOT NULL,
RUTA VARCHAR(100) NULL,
ICONO VARCHAR(25) NULL,
ORDEN NUMBER(10) NOT NULL
);

CREATE SEQUENCE PERMISO_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE ROL(
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) UNIQUE NOT NULL
);

CREATE SEQUENCE ROL_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE ROL_PERMISO(
ID INTEGER PRIMARY KEY NOT NULL,
ID_ROL INTEGER NOT NULL,
ID_PERMISO INTEGER NOT NULL,
FOREIGN KEY(ID_ROL) REFERENCES ROL(ID),
FOREIGN KEY(ID_PERMISO) REFERENCES PERMISO(ID)
);

CREATE SEQUENCE ROL_PERMISO_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE USUARIO(
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APE_PATERNO VARCHAR(50) NOT NULL,
APE_MATERNO VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NULL,
TELEFONO VARCHAR(20) NULL
);

CREATE SEQUENCE USUARIO_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE USUARIO_ROL(
ID_ROL INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,
PRIMARY KEY(ID_ROL,ID_USUARIO),
FOREIGN KEY(ID_ROL) REFERENCES ROL(ID),
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);

INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ICONO,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Home','/intranet/home','home',1);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ICONO,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Venta','/intranet/venta','add_shopping_cart',2);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ICONO,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Personal','/intranet/personal','group',3);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ICONO,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Administracion','/intranet/administracion','layers',4);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ICONO,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Reportes','/intranet/reportes','airplay',5);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,3,'Registrar Insumos','/intranet/personal/insumos',1);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,3,'Calcular honorarios','/intranet/personal/honorarios',2);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,3,'Registrar Personal','/intranet/personal/persona',3);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,4,'Registrar producto (Panes)','/intranet/administracion/productos',1);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,4,'Registrar Tipos Insumo','/intranet/administracion/tipos-insumo',2);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,4,'Registrar numeracion ticket','/intranet/administracion/comprobantes',3);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,4,'Registrar parametros','/intranet/administracion/maestras',4);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,5,'Resumen ventas','/intranet/reportes/ventas',1);


INSERT INTO ROL(ID,NOMBRE) VALUES (ROL_SEQ.NEXTVAL,'ADMIN_ROLE');

INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,1);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,2);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,3);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,4);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,5);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,6);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,7);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,8);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,9);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,10);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,11);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,12);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,13);

INSERT INTO USUARIO(ID,NOMBRE,APE_PATERNO,APE_MATERNO,USERNAME,PASSWORD,EMAIL,TELEFONO)
VALUES(USUARIO_SEQ.NEXTVAL,'NERIO','BAEZ','DELGADO','superadmin','$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.','NBAEZ001@GMAIL.COM','929181954');
INSERT INTO USUARIO(ID,NOMBRE,APE_PATERNO,APE_MATERNO,USERNAME,PASSWORD,EMAIL,TELEFONO)
VALUES(USUARIO_SEQ.NEXTVAL,'KITE','DANIE','DANIE','admin','$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.','NBAEZ001@GMAIL.COM','929181954');

INSERT INTO USUARIO_ROL(ID_USUARIO,ID_ROL) VALUES (1,1);
INSERT INTO USUARIO_ROL(ID_USUARIO,ID_ROL) VALUES (2,1);
COMMIT;

CREATE OR REPLACE PACKAGE PCK_PSEG_AUTENTICACION AS

    PROCEDURE SP_BUSCAR_USUARIO (
        I_USERNAME  IN   VARCHAR2,
        R_RESULT     OUT   SYS_REFCURSOR,
        R_RESULT_DET OUT   SYS_REFCURSOR,
        R_CODIGO    OUT   NUMBER,
        R_MENSAJE   OUT   VARCHAR2
    );
	
	PROCEDURE SP_L_PERMISO (
        I_ID_USUARIO   IN   NUMBER,
        R_RESULT       OUT   SYS_REFCURSOR,
        R_CODIGO       OUT   NUMBER,
        R_MENSAJE      OUT   VARCHAR2
    );
	
END PCK_PSEG_AUTENTICACION;
/     
CREATE OR REPLACE PACKAGE BODY PCK_PSEG_AUTENTICACION AS

    PROCEDURE SP_BUSCAR_USUARIO (
        I_USERNAME  IN   VARCHAR2,
        R_RESULT     OUT   SYS_REFCURSOR,
        R_RESULT_DET OUT   SYS_REFCURSOR,
        R_CODIGO    OUT   NUMBER,
        R_MENSAJE   OUT   VARCHAR2
    ) AS
    BEGIN
        OPEN R_RESULT FOR
            SELECT
                    U.ID,
                    U.NOMBRE,
                    U.APE_PATERNO,
                    U.APE_MATERNO,
                    U.USERNAME,
                    U.PASSWORD,
                    U.EMAIL,
                    U.TELEFONO
            FROM PSEG.USUARIO U
            WHERE U.USERNAME=I_USERNAME;
       
        OPEN R_RESULT_DET FOR
            SELECT R.ID,R.NOMBRE FROM PSEG.USUARIO U
            LEFT JOIN PSEG.USUARIO_ROL UR ON UR.ID_USUARIO = U.ID
            LEFT JOIN PSEG.ROL R ON R.ID = UR.ID_ROL
            WHERE U.USERNAME=I_USERNAME;

        R_CODIGO := SQLCODE;
        R_MENSAJE := SQLERRM;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            R_CODIGO := SQLCODE;
            R_MENSAJE := SQLERRM;
    END SP_BUSCAR_USUARIO;
	
	PROCEDURE SP_L_PERMISO (
        I_ID_USUARIO   IN    NUMBER,
        R_RESULT       OUT   SYS_REFCURSOR,
        R_CODIGO       OUT   NUMBER,
        R_MENSAJE      OUT   VARCHAR2
    ) AS
    BEGIN
        OPEN R_RESULT FOR
            SELECT
			DISTINCT(P.ID) AS ID,
			P.ID_PADRE,
			P.NOMBRE,
			P.RUTA,
			P.ICONO,
			P.ORDEN
            FROM PSEG.USUARIO U
            INNER JOIN PSEG.USUARIO_ROL UR ON UR.ID_USUARIO = U.ID
            INNER JOIN PSEG.ROL R ON R.ID = UR.ID_ROL
			INNER JOIN PSEG.ROL_PERMISO RP ON RP.ID_ROL=R.ID
			INNER JOIN PSEG.PERMISO P ON P.ID=RP.ID_PERMISO
            WHERE U.ID=I_ID_USUARIO 
			ORDER BY P.ORDEN ASC;

        R_CODIGO := SQLCODE;
        R_MENSAJE := SQLERRM;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            R_CODIGO := SQLCODE;
            R_MENSAJE := SQLERRM;
    END SP_L_PERMISO;

END PCK_PSEG_AUTENTICACION;
/