DROP PACKAGE PCK_PSEG_AUTENTICACION;

DROP SEQUENCE ROL_PERMISO_SEQ;
DROP SEQUENCE USUARIO_SEQ;
DROP SEQUENCE ROL_SEQ;
DROP SEQUENCE PERMISO_SEQ;

DROP TABLE USUARIO_ROL;
DROP TABLE ROL_PERMISO;
DROP TABLE USUARIO;
DROP TABLE ROL;
DROP TABLE PERMISO;