CREATE TABLE PERMISO(
ID INTEGER PRIMARY KEY NOT NULL,
ID_PADRE INTEGER NULL,
NOMBRE VARCHAR(100) NOT NULL,
RUTA VARCHAR(100) NULL,
ORDEN NUMBER(10) NOT NULL
);

CREATE SEQUENCE PERMISO_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE ROL(
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) UNIQUE NOT NULL
);

CREATE SEQUENCE ROL_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE ROL_PERMISO(
ID INTEGER PRIMARY KEY NOT NULL,
ID_ROL INTEGER NOT NULL,
ID_PERMISO INTEGER NOT NULL,
FOREIGN KEY(ID_ROL) REFERENCES ROL(ID),
FOREIGN KEY(ID_PERMISO) REFERENCES PERMISO(ID)
);

CREATE SEQUENCE ROL_PERMISO_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE USUARIO(
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APE_PATERNO VARCHAR(50) NOT NULL,
APE_MATERNO VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NULL,
TELEFONO VARCHAR(20) NULL
);

CREATE SEQUENCE USUARIO_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE TABLE USUARIO_ROL(
ID_ROL INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,
PRIMARY KEY(ID_ROL,ID_USUARIO),
FOREIGN KEY(ID_ROL) REFERENCES ROL(ID),
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);

INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Home','/intranet/home',1);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Venta','/intranet/venta',2);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,NULL,'Administracion','/intranet/venta',3);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,3,'Registrar producto','/intranet/administracion/productos',1);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,3,'Registrar numeracion ticket','/intranet/administracion/comprobantes',2);
INSERT INTO PERMISO (ID,ID_PADRE,NOMBRE,RUTA,ORDEN) VALUES (PERMISO_SEQ.NEXTVAL,3,'Registrar parametros','/intranet/administracion/maestras',3);

INSERT INTO ROL(ID,NOMBRE) VALUES (ROL_SEQ.NEXTVAL,'ADMIN_ROLE');

INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,1);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,2);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,3);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,4);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,5);
INSERT INTO ROL_PERMISO(ID,ID_ROL,ID_PERMISO) VALUES (ROL_PERMISO_SEQ.NEXTVAL,1,6);

INSERT INTO USUARIO(ID,NOMBRE,APE_PATERNO,APE_MATERNO,USERNAME,PASSWORD,EMAIL,TELEFONO)
VALUES(USUARIO_SEQ.NEXTVAL,'NERIO','BAEZ','DELGADO','superadmin','$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.','NBAEZ001@GMAIL.COM','929181954');
INSERT INTO USUARIO(ID,NOMBRE,APE_PATERNO,APE_MATERNO,USERNAME,PASSWORD,EMAIL,TELEFONO)
VALUES(USUARIO_SEQ.NEXTVAL,'KITE','DANIE','DANIE','admin','$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.','NBAEZ001@GMAIL.COM','929181954');

INSERT INTO USUARIO_ROL(ID_USUARIO,ID_ROL) VALUES (1,1);
INSERT INTO USUARIO_ROL(ID_USUARIO,ID_ROL) VALUES (2,1);
COMMIT;