DROP PACKAGE PCK_PPOS_ADMINISTRACION;
DROP PACKAGE PCK_PPOS_PERSONAL;
DROP PACKAGE PCK_PPOS_UBIGEO;
DROP PACKAGE PCK_PPOS_VENTA;

DROP TYPE TB_DETALLE_VENTA;
DROP TYPE T_DETALLE_VENTA;

DROP SEQUENCE SEQ_PERSONAL;
DROP SEQUENCE SEQ_PERSONA;
DROP SEQUENCE SEQ_COMPROBANTE;
DROP SEQUENCE SEQ_DETALLE_VENTA;
DROP SEQUENCE SEQ_VENTA;
DROP SEQUENCE SEQ_PRODUCTO;
DROP SEQUENCE SEQ_MAESTRA;
DROP SEQUENCE SEQ_DISTRITO;
DROP SEQUENCE SEQ_PROVINCIA;
DROP SEQUENCE SEQ_DEPARTAMENTO;
DROP SEQUENCE SEQ_PAIS;

DROP TABLE PERSONAL;
DROP TABLE PERSONA;
DROP TABLE COMPROBANTE;
DROP TABLE DETALLE_VENTA;
DROP TABLE VENTA;
DROP TABLE PRODUCTO;
DROP TABLE MAESTRA;
DROP TABLE DISTRITO;
DROP TABLE PROVINCIA;
DROP TABLE DEPARTAMENTO;
DROP TABLE PAIS;