CREATE OR REPLACE PACKAGE PCK_PPOS_VENTA AS

    PROCEDURE SP_I_VENTA (
		I_ID_COMPROBANTE		IN 		NUMBER,
		I_TOTAL		 			IN 		DECIMAL,
		I_FLG_ACTIVO 			IN 		NUMBER,
        I_ID_USUARIO_CREA       IN      NUMBER,
        I_FEC_USUARIO_CREA      IN      VARCHAR2,
		I_DETALLE_VENTA        	IN      VARCHAR2,
        R_ID                    OUT     NUMBER,
		R_SERIE           		OUT     VARCHAR2,
		R_NUMERO  				OUT     VARCHAR2,
        R_CODIGO                OUT     NUMBER,
        R_MENSAJE               OUT     VARCHAR2
    );

    PROCEDURE SP_L_VENTA (
        R_LISTA               OUT     SYS_REFCURSOR,
        R_CODIGO              OUT     NUMBER,
        R_MENSAJE             OUT     VARCHAR2
    );

END PCK_PPOS_VENTA;
/
CREATE OR REPLACE PACKAGE BODY PCK_PPOS_VENTA AS

    PROCEDURE SP_I_VENTA (
		I_ID_COMPROBANTE		IN 		NUMBER,
		I_TOTAL		 			IN 		DECIMAL,
		I_FLG_ACTIVO 			IN 		NUMBER,
        I_ID_USUARIO_CREA       IN      NUMBER,
        I_FEC_USUARIO_CREA      IN      VARCHAR2,
		I_DETALLE_VENTA        	IN      VARCHAR2,
        R_ID                    OUT     NUMBER,
		R_SERIE           		OUT     VARCHAR2,
		R_NUMERO  				OUT     VARCHAR2,
        R_CODIGO                OUT     NUMBER,
        R_MENSAJE               OUT     VARCHAR2
    ) AS
	V_NUMERO NUMBER;
	CURSOR C_DETALLE_VENTA IS 
		SELECT
        REGEXP_SUBSTR(DETALLE_VENTA,'([^,]+)',1,1,'',1) AS ID_PRODUCTO,
        REGEXP_SUBSTR(DETALLE_VENTA,'([^,]+)',1,2,'',1) AS CANTIDAD,
        REGEXP_SUBSTR(DETALLE_VENTA,'([^,]+)',1,3,'',1) AS PRECIO,
        REGEXP_SUBSTR(DETALLE_VENTA,'([^,]+)',1,4,'',1) AS SUBTOTAL,
        REGEXP_SUBSTR(DETALLE_VENTA,'([^,]+)',1,5,'',1) AS FLG_ACTIVO
        FROM (
            SELECT 
            REGEXP_SUBSTR(I_DETALLE_VENTA,'[^|]+',1,LEVEL) AS DETALLE_VENTA 
            FROM DUAL 
            CONNECT BY REGEXP_SUBSTR(I_DETALLE_VENTA,'[^|]+',1,LEVEL) IS NOT NULL
        );
    BEGIN
		SELECT LPAD(C.SERIE, C.LONG_SERIE, '0'), LPAD(C.NUMERO, C.LONG_NUMERO, '0'), (C.NUMERO + 1) INTO R_SERIE, R_NUMERO, V_NUMERO FROM COMPROBANTE C WHERE C.ID=I_ID_COMPROBANTE;
		UPDATE COMPROBANTE C SET
		C.NUMERO = V_NUMERO
		WHERE C.ID=I_ID_COMPROBANTE;
		
        SELECT SEQ_VENTA.NEXTVAL INTO R_ID FROM DUAL;

        INSERT INTO VENTA(
        ID,
		SERIE,
        NUMERO,
		TOTAL,
        FLG_ACTIVO,
        ID_USUARIO_CREA,
        FEC_USUARIO_CREA)
        VALUES(
        R_ID,
		R_SERIE,
        R_NUMERO,
		I_TOTAL,
        I_FLG_ACTIVO,
        I_ID_USUARIO_CREA,
        TO_DATE(I_FEC_USUARIO_CREA,'DD/MM/YYYY'));
		
		FOR V_ITEM IN C_DETALLE_VENTA LOOP
			INSERT INTO DETALLE_VENTA(
			ID,
			ID_VENTA,
			ID_PRODUCTO,
			CANTIDAD,
			PRECIO,
			SUBTOTAL,
			FLG_ACTIVO)
            VALUES(
			SEQ_DETALLE_VENTA.NEXTVAL,
			R_ID,
			V_ITEM.ID_PRODUCTO,
			TO_NUMBER(V_ITEM.CANTIDAD, '9999999.9'),
			TO_NUMBER(V_ITEM.PRECIO, '9999999.99'),
			TO_NUMBER(V_ITEM.SUBTOTAL, '9999999.99'),
			V_ITEM.FLG_ACTIVO);
		END LOOP;

        COMMIT;

        R_CODIGO := SQLCODE;
        R_MENSAJE := SQLERRM;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            R_CODIGO := SQLCODE;
            R_MENSAJE := SQLERRM;
	END SP_I_VENTA;

    PROCEDURE SP_L_VENTA (
        R_LISTA               OUT     SYS_REFCURSOR,
        R_CODIGO              OUT     NUMBER,
        R_MENSAJE             OUT     VARCHAR2
    ) AS
        V_SQL VARCHAR2(30000);
    BEGIN
        V_SQL := 'SELECT
		C.ID,
		C.SERIE,
		C.NUMERO,
		C.TOTAL,
		C.FLG_ACTIVO,
		C.ID_USUARIO_CREA,
		C.FEC_USUARIO_CREA,
		C.ID_USUARIO_MOD,
		C.FEC_USUARIO_MOD
        FROM VENTA C
        WHERE 1=1
		ORDER BY C.ID DESC';

        OPEN R_LISTA FOR V_SQL;

        R_CODIGO := SQLCODE;
        R_MENSAJE := SQLERRM;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            R_CODIGO := SQLCODE;
            R_MENSAJE := SQLERRM;
    END SP_L_VENTA;

END PCK_PPOS_VENTA;
/