CREATE TABLE MAESTRA(
    ID INTEGER NOT NULL PRIMARY KEY,
    ID_MAESTRA INTEGER NULL,
    ID_TABLA NUMBER(10) NOT NULL,
    ID_ITEM NUMBER(10) NOT NULL,
    ORDEN NUMBER(10) NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    VALOR VARCHAR(100) NULL,
    FLAG_ACTIVO NUMBER(1) NOT NULL,
	DESCRIPCION VARCHAR(250) NULL,
    ID_USUARIO_CREA INTEGER NOT NULL,
    FEC_USUARIO_CREA DATE NOT NULL,
    ID_USUARIO_MOD INTEGER NULL,
    FEC_USUARIO_MOD DATE NULL
);

CREATE SEQUENCE SEQ_MAESTRA
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
INSERT INTO MAESTRA(ID,ID_MAESTRA,ID_TABLA,ID_ITEM,ORDEN,CODIGO,NOMBRE,VALOR,FLAG_ACTIVO,DESCRIPCION,ID_USUARIO_CREA,FEC_USUARIO_CREA) VALUES(SEQ_MAESTRA.NEXTVAL,0,1,0,0,'UM','UNIDAD MEDIDA',NULL,1,NULL,1,SYSDATE);
INSERT INTO MAESTRA(ID,ID_MAESTRA,ID_TABLA,ID_ITEM,ORDEN,CODIGO,NOMBRE,VALOR,FLAG_ACTIVO,DESCRIPCION,ID_USUARIO_CREA,FEC_USUARIO_CREA) VALUES(SEQ_MAESTRA.NEXTVAL,0,2,0,0,'TC','TIPO COMPROBANTE',NULL,1,NULL,1,SYSDATE);
INSERT INTO MAESTRA(ID,ID_MAESTRA,ID_TABLA,ID_ITEM,ORDEN,CODIGO,NOMBRE,VALOR,FLAG_ACTIVO,DESCRIPCION,ID_USUARIO_CREA,FEC_USUARIO_CREA) VALUES(SEQ_MAESTRA.NEXTVAL,0,3,0,0,'TD','TIPO DOCUMENTO',NULL,1,NULL,1,SYSDATE);
INSERT INTO MAESTRA(ID,ID_MAESTRA,ID_TABLA,ID_ITEM,ORDEN,CODIGO,NOMBRE,VALOR,FLAG_ACTIVO,DESCRIPCION,ID_USUARIO_CREA,FEC_USUARIO_CREA) VALUES(SEQ_MAESTRA.NEXTVAL,0,4,0,0,'SX','SEXO',NULL,1,NULL,1,SYSDATE);
commit;

CREATE TABLE PRODUCTO(
ID INTEGER NOT NULL PRIMARY KEY,
IDT_UNIDAD_MEDIDA INTEGER NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
CODIGO VARCHAR(50) NULL,
PRECIO NUMBER(8,2) NOT NULL,
FLG_ACTIVO NUMBER(1) NOT NULL,
ID_USUARIO_CREA INTEGER NOT NULL,
FEC_USUARIO_CREA DATE NOT NULL,
ID_USUARIO_MOD INTEGER NULL,
FEC_USUARIO_MOD DATE NULL
);

CREATE SEQUENCE SEQ_PRODUCTO
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE TABLE VENTA(
ID INTEGER NOT NULL PRIMARY KEY,
SERIE VARCHAR(10) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
TOTAL NUMBER(8,2) NOT NULL,
FLG_ACTIVO NUMBER(1) NOT NULL,
ID_USUARIO_CREA INTEGER NOT NULL,
FEC_USUARIO_CREA DATE NOT NULL,
ID_USUARIO_MOD INTEGER NULL,
FEC_USUARIO_MOD DATE NULL
);

CREATE SEQUENCE SEQ_VENTA
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE TABLE DETALLE_VENTA(
ID INTEGER NOT NULL PRIMARY KEY,
ID_VENTA INTEGER NOT NULL,
ID_PRODUCTO INTEGER NOT NULL,
CANTIDAD NUMBER(6,1) NOT NULL,
PRECIO NUMBER(8,2) NOT NULL,
SUBTOTAL NUMBER(8,2) NOT NULL,
FLG_ACTIVO NUMBER(1) NOT NULL,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID)
);

CREATE SEQUENCE SEQ_DETALLE_VENTA
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE TABLE COMPROBANTE(
    ID INTEGER NOT NULL PRIMARY KEY,
	IDT_TIPO_COMPROBANTE INTEGER NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
	SERIE NUMBER(10) NOT NULL,
    NUMERO NUMBER(10) NOT NULL,
    LONG_SERIE NUMBER(10) NOT NULL,
	LONG_NUMERO NUMBER(10) NOT NULL,
	FLG_ACTUAL NUMBER(1) NOT NULL,
    FLG_ACTIVO NUMBER(1) NOT NULL,
	FLG_USADO NUMBER(1) NOT NULL,
    ID_USUARIO_CREA INTEGER NOT NULL,
    FEC_USUARIO_CREA DATE NOT NULL,
    ID_USUARIO_MOD INTEGER NULL,
    FEC_USUARIO_MOD DATE NULL
);

CREATE SEQUENCE SEQ_COMPROBANTE
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  

CREATE TABLE PERSONA(
    ID INTEGER NOT NULL PRIMARY KEY,
	IDT_TIPO_DOCUMENTO INTEGER NULL,
	IDT_SEXO INTEGER NULL,
    ID_PAIS NUMBER(10) NULL,
	ID_DEPARTAMENTO NUMBER(10) NULL,
	ID_PROVINCIA NUMBER(10) NULL,
	ID_DISTRITO NUMBER(10) NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APE_PATERNO VARCHAR(50) NULL,
	APE_MATERNO VARCHAR(50) NULL,
	NRO_DOCUMENTO VARCHAR(15) NOT NULL,
	DIRECCION_DOMICILIO VARCHAR(100) NULL,
	FEC_NACIMIENTO DATE NULL
);

CREATE SEQUENCE SEQ_PERSONA
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE TABLE PERSONAL(
ID INTEGER NOT NULL PRIMARY KEY,
ID_PERSONA INTEGER NOT NULL,
CARGO VARCHAR(50) NOT NULL,
FLG_ACTIVO NUMBER(1) NOT NULL,
ID_USUARIO_CREA INTEGER NOT NULL,
FEC_USUARIO_CREA DATE NOT NULL,
ID_USUARIO_MOD INTEGER NULL,
FEC_USUARIO_MOD DATE NULL,
FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID)
);

CREATE SEQUENCE SEQ_PERSONAL
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;